export const FLORIDA_CITIES = [
  "Jacksonville",
  "Miami",
  "Tampa",
  "Orlando",
  "St. Petersburg",
  "Hialeah",
  "Port St. Lucie",
  "Cape Coral",
  "Tallahassee",
  "Fort Lauderdale",
  "Pembroke Pines",
  "Hollywood",
  "Gainesville",
  "Miramar",
  "Coral Springs",
  "Palm Bay",
  "West Palm Beach",
  "Clearwater",
  "Lakeland",
  "Pompano Beach",
  "Miami Gardens",
  "Davie",
  "Boca Raton",
  "Sunrise",
  "Plantation",
  "Fort Myers",
  "Sarasota",
  "Pensacola",
  "Ocala",
  "Palm Coast",
  "Kissimmee",
  "Daytona Beach",
  "Sanford",
  "Bradenton",
  "Melbourne",
] as const;
