export const CITIES_BY_STATE: Record<string, readonly string[]> = {
  alabama: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa", "Auburn", "Dothan", "Hoover"],
  alaska: ["Anchorage", "Fairbanks", "Juneau", "Wasilla", "Sitka", "Ketchikan"],
  arizona: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Gilbert", "Glendale", "Tempe", "Peoria", "Flagstaff"],
  arkansas: ["Little Rock", "Fayetteville", "Fort Smith", "Springdale", "Jonesboro", "Rogers", "Conway"],
  california: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento", "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Riverside", "Irvine"],
  colorado: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Boulder", "Pueblo"],
  connecticut: ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury", "Norwalk", "Danbury"],
  delaware: ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"],
  florida: [
    "Jacksonville",
    "Miami",
    "Tampa",
    "Orlando",
    "St. Petersburg",
    "Hialeah",
    "Port St. Lucie",
    "Cape Coral",
    "Tallahassee",
    "Fort Lauderdale",
    "Pembroke Pines",
    "Hollywood",
    "Gainesville",
    "Miramar",
    "Coral Springs",
    "Palm Bay",
    "West Palm Beach",
    "Clearwater",
    "Lakeland",
    "Pompano Beach",
    "Fort Myers",
    "Sarasota",
    "Pensacola",
    "Ocala",
    "Kissimmee",
    "Daytona Beach",
    "Melbourne",
  ],
  georgia: ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah", "Athens", "Sandy Springs", "Roswell"],
  hawaii: ["Honolulu", "Hilo", "Kailua", "Kapolei", "Kahului", "Kihei"],
  idaho: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello", "Coeur d'Alene", "Twin Falls"],
  illinois: ["Chicago", "Aurora", "Naperville", "Joliet", "Rockford", "Springfield", "Elgin", "Peoria"],
  indiana: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel", "Bloomington", "Fishers"],
  iowa: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City", "Waterloo", "Ames"],
  kansas: ["Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka", "Lawrence"],
  kentucky: ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington", "Richmond"],
  louisiana: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles", "Kenner"],
  maine: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn", "Biddeford"],
  maryland: ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie", "Annapolis", "Silver Spring"],
  massachusetts: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton", "Quincy"],
  michigan: ["Detroit", "Grand Rapids", "Warren", "Ann Arbor", "Lansing", "Sterling Heights", "Dearborn"],
  minnesota: ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington", "Brooklyn Park"],
  mississippi: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi", "Meridian"],
  missouri: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence", "Lee's Summit"],
  montana: ["Billings", "Missoula", "Great Falls", "Bozeman", "Helena", "Kalispell"],
  nebraska: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
  nevada: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks", "Carson City"],
  "new-hampshire": ["Manchester", "Nashua", "Concord", "Dover", "Rochester", "Keene"],
  "new-jersey": ["Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton", "Camden", "Atlantic City"],
  "new-mexico": ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"],
  "new-york": ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany", "New Rochelle"],
  "north-carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary", "Wilmington", "Asheville"],
  "north-dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
  ohio: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton", "Parma"],
  oklahoma: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond", "Lawton"],
  oregon: ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro", "Bend", "Beaverton"],
  pennsylvania: ["Philadelphia", "Pittsburgh", "Allentown", "Harrisburg", "Erie", "Reading", "Scranton"],
  "rhode-island": ["Providence", "Warwick", "Cranston", "Pawtucket", "Newport"],
  "south-carolina": ["Charleston", "Columbia", "North Charleston", "Mount Pleasant", "Greenville", "Rock Hill", "Myrtle Beach"],
  "south-dakota": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"],
  tennessee: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro", "Franklin"],
  texas: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Lubbock"],
  utah: ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem", "Sandy", "Ogden", "St. George"],
  vermont: ["Burlington", "South Burlington", "Rutland", "Essex", "Montpelier"],
  virginia: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Alexandria", "Hampton", "Roanoke"],
  washington: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent", "Everett", "Olympia"],
  "west-virginia": ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
  wisconsin: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton", "Eau Claire"],
  wyoming: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
};

export const FLORIDA_CITIES = CITIES_BY_STATE.florida;

export function getCitiesForState(stateSlug: string): string[] {
  return [...(CITIES_BY_STATE[stateSlug.toLowerCase()] || [])];
}
